### ISSUE TITLE
Support for React-Native?

### ISSUE THREAD

**Issue by gotoAndBliss** [TheRusskiy/pusher-redux#1]
Nice stuff. Looks like it's just a subtle adjustment to make it ReactNative compliant 

```javascript
import Pusher from 'pusher-js/react-native';
```

**Comment by TheRusskiy** [comment]
@gotoAndBliss I made changes but have not tested them with react native.
Go ahead and update to `0.1.1`.
Here are instructions: https://github.com/TheRusskiy/pusher-redux#react-native

**Comment by TheRusskiy** [comment]
@gotoAndBliss going to close the issue
