### ISSUE TITLE
`disconnected` setting `isConnected` to `true`?

### ISSUE THREAD

**Issue by feifanzhou** [TheRusskiy/pusher-redux#17]
Is [this line](https://github.com/TheRusskiy/pusher-redux/blob/690e5560baeafe9099ba928d55033c3b0b4a2ad3/lib/pusher-redux.js#L59) correct? It seems like `isConnected` should be set to `false` in the `disconnected` function …

**Comment by TheRusskiy** [comment]
@feifanzhou oops, sorry, missed the issue :-)
As for the line in question it was actually irrelevant in this case. 
The purpose of "isConnected" was to run pending functions after pusher is "configured" if there's a delayed config present.
I removed the line so it's not confusing
