### ISSUE TITLE
Missing Connection States?

### ISSUE THREAD

**Issue by mattfordham** [TheRusskiy/pusher-redux#18]
Could you confirm that the only Pusher "client connection states" accounted for by this library are "connected" and "disconnected"? I am successfully using this library, but am now needing to account for additional states, such as "failed" and "unavailable".

For reference:
https://pusher.com/docs/client_api_guide/client_connect#available-states

Thanks!

**Comment by TheRusskiy** [comment]
@mattfordham 
These 2 are the most commonly used states.
If you need other ones I will happily accept a PR (or do one myself, when have some free time)

**Comment by mattfordham** [comment]
Great, thanks! They seem easy enough to add. I'll submit a PR if/when I'm able.

**Comment by jfulse** [comment]
Created a PR here: https://github.com/TheRusskiy/pusher-redux/pull/20

**Comment by TheRusskiy** [comment]
🎉
