### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by pejowei** [TheRusskiy/pusher-redux#19]
Hi, 

Github is sending me notifications that there is a high-severity security vulnerability in this package.

from github:
```
known high severity security vulnerability detected in lodash.template < 4.5.0 defined in yarn.lock.
--
yarn.lock update suggested: lodash.template ~> 4.5.0.
Always verify the validity and compatibility of suggestions with your codebase.
```

Looks like it should just be a dependency upgrade.  Is there any easy way for you to upgrade the dependency in the pusher-redux package?  Is there an easy way for me to force the dependency to be a higher version on my end?

Apologies if I am overlooking some obvious solution, I'm not great at packaging etc.

Cheers,
peter

**Comment by TheRusskiy** [comment]
@pejowei turns out yarn.lock was out of date, this package does not use lodash.
I published a new 0.3.10 version with fixed yarn.lock.
Thanks for reporting and let me know if you have further concerns.
