### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by charlie-ablett** [TheRusskiy/pusher-redux#3]
Hi, your library works great on development - very happy! My nodejs/npm isn't my primary skill set, so let me know if I'm making any noob errors. I'm working on a project that uses webpack, react and redux.

I'm using `pusher-redux` and installed `pusher-js` separately since (IIRC) it oddly didn't install automatically as a dependency. The library works great on dev, though it does give me the following error:

    var btoa = (window).btoa || function (b) {
	                         ^
    ReferenceError: window is not defined
    at Object.<anonymous> (/home/user/project/node_modules/pusher-redux/node_modules/pusher-js/dist/web/pusher.js:890:27)
    at __webpack_require__ (/home/user/project/node_modules/pusher-redux/node_modules/pusher-js/dist/web/pusher.js:38:30)
    at Object.<anonymous> (/home/user/project/node_modules/pusher-redux/node_modules/pusher-js/dist/web/pusher.js:638:17)
    at __webpack_require__ (/home/user/project/node_modules/pusher-redux/node_modules/pusher-js/dist/web/pusher.js:38:30)
    ....<snip>

This is the identical error to [this error on pusher-js](https://github.com/pusher/pusher-js/issues/183).

I see the error happening on the dev box, but `npm start -s` doesn't choke on it, and runs things fine anyway. However, when I run `npm run build`, the error is fatal and it doesn't complete the process of generating the resulting dist files.

Versions:
    "pusher-redux": "0.1.1"

Do you have any suggestions?

Many thanks!

**Comment by TheRusskiy** [comment]
interesting, I am using this with webpack in production and no issues so far :-/

**Comment by charlie-ablett** [comment]
I cleared out `node_modules` and reinstalled, and still getting this error. I then updated most modules so they were more recent, and I'm still getting it. I followed your readme and am still getting this issue. It's frustrating because it looks like something "low-level" and not something I can really figure out without deep understanding of pusher-js and your library (and es6/nodejs, which I don't have). 

Here's how I'm instantiating it:

```
import { createStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import rootReducer from '../reducers';
import { configurePusher } from 'pusher-redux';
const options = {
  appKey: SLANGER_APP_KEY,
  httpHost: SLANGER_HTTP_HOST,
  httpPort: SLANGER_HTTP_PORT,
  wsHost: SLANGER_WEB_HOST,
  wsPort: SLANGER_WEB_PORT
};

export function setupPusher(store) {
  configurePusher(store, SLANGER_APP_KEY, options);
}

export default function configureStore(initialState) {
  // return createStore(rootReducer, initialState);

  let store = createStore(rootReducer, initialState, compose(
    applyMiddleware(thunk),
    )
  );

  setupPusher(store);
  return store;
}
```

Dependency list:

    "connect-history-api-fallback": "1.3.0",
    "file-downloader": "2.1.0",
    "font-awesome": "4.7.0",
    "font-awesome-webpack": "0.0.4",
    "less": "2.7.1",
    "lodash": "4.17.2",
    "moment": "2.17.0",
    "object-assign": "4.1.0",
    "pusher-redux": "0.1.1",
    "react": "15.4.1",
    "react-dom": "15.4.1",
    "react-redux": "4.4.6",
    "react-router": "3.0.0",
    "react-select": "1.0.0-rc.3",
    "react-timeago": "3.1.3",
    "redux": "3.6.0",
    "redux-api-middleware": "1.0.2",
    "redux-thunk": "2.1.0",
    "resolve-url-loader": "1.6.0",
    "url-loader": "0.5.7"

Dev dependencies:

    "babel-cli": "6.24.0",
    "babel-core": "6.24.0",
    "babel-eslint": "7.1.1",
    "babel-loader": "6.4.1",
    "babel-plugin-react-display-name": "2.0.0",
    "babel-plugin-react-transform": "2.0.2",
    "babel-preset-es2015": "6.24.0",
    "babel-preset-react": "6.23.0",
    "babel-preset-stage-1": "6.22.0",
    "browser-sync": "2.18.8",
    "chai": "3.5.0",
    "cheerio": "0.22.0",
    "colors": "1.1.2",
    "cross-env": "3.2.4",
    "css-loader": "0.27.3",
    "eslint": "3.17.1",
    "eslint-loader": "1.6.3",
    "eslint-plugin-react": "6.10.0",
    "extract-text-webpack-plugin": "2.1.0",
    "file-loader": "0.10.1",
    "gulp": "3.9.1",
    "gulp-concat": "2.6.1",
    "gulp-if": "2.0.2",
    "gulp-jshint": "2.0.4",
    "gulp-prompt": "0.2.0",
    "gulp-rename": "1.2.2",
    "gulp-rsync": "0.0.7",
    "gulp-sass": "3.1.0",
    "gulp-uglify": "2.1.0",
    "gulp-util": "3.0.8",
    "jshint": "2.9.4",
    "minimist": "1.2.0",
    "mocha": "3.2.0",
    "node-sass": "4.5.0",
    "parallelshell": "2.0.0",
    "react-transform-catch-errors": "1.0.2",
    "react-transform-hmr": "1.0.4",
    "redbox-react": "1.3.4",
    "rimraf": "2.6.1",
    "sass-loader": "6.0.3",
    "style-loader": "0.14.1",
    "url-loader": "0.5.7",
    "watch": "1.0.2",
    "webpack": "2.2.1",
    "webpack-dev-middleware": "1.10.1",
    "webpack-hot-middleware": "2.17.1",
    "yargs": "7.0.2"

**Comment by charlie-ablett** [comment]
@TheRusskiy ^^

**Comment by charlie-ablett** [comment]
Is there any way to instantiate `pusher-redux` when there "is a window"? I'm not sure why it doesn't think there is a browser (presumably because it is writing the main js file)... can you comment?

**Comment by charlie-ablett** [comment]
Turns out this issue is with the wrong target (`node` rather than `web`) when it was attempting to run tests.

**Comment by maxparelius** [comment]
Also had this issue due to server side rendering. Window is not present when my component gets rendered server side. My solution was to wait till component had mounted client side to ensure window was present as follows:

```
componentDidMount() {
  const { subscribe } = require('pusher-redux');
  subscribe(...);
}

componentWillUnmount() {
  const { unsubscribe } = require('pusher-redux');
  unsubscribe(...);
}
```
