### ISSUE TITLE
On Pusher connected event dispatch a redux action

### ISSUE THREAD

**Issue by koox00** [TheRusskiy/pusher-redux#5]
Hi,  
I think it would be very useful to be able to dispatch a redux action upon pusher connect.
My usecase is that I need the socket id, which pusher returns upon connection, to save it in the redux store.  

This is particulary helpful in the case that you want to emit events to all, even me, but exclude only the connection with the particular socket id.

**Comment by TheRusskiy** [comment]
Hey, nice idea.
I am not feeling well this week, hopefully gonna feel better by weekends. 
If you don't want to wait until then feel free to make a pull request ;-)

**Comment by koox00** [comment]
Nice, I'm glad you like it. 
I will try a pull request then in the following days!

PS: I hope you'll feel better soon!

**Comment by TheRusskiy** [comment]
@koox00 sorry for the delay, added this in the latest version
